# Generated by Django 5.1.4 on 2024-12-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='numero_habitacion',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
